ibase_payment:
    resource: "@IbasePaymentBundle/Resources/config/routing.yml"
    prefix:   /

ibase_app:
    resource: "@IbaseAppBundle/Resources/config/routing.yml"
    prefix:   /

ibase_mail:
    resource: "@IbaseMailBundle/Resources/config/routing.yml"
    prefix:   /

ibase_cart:
    resource: "@IbaseCartBundle/Resources/config/routing.yml"
    prefix:   /

ibase_store:
    resource: "@IbaseStoreBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
#Login routing
login:
    pattern: /login
    defaults: { _controller: IbaseAppBundle:Security:login }
 
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout

#payumbundle routing
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    
payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"