<?php

namespace Ibase\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
   public function getPurchaseWithDate($period) {

      $qb = $this->createQueryBuilder('p')
        ->where('p.createdAt > :date')
        ->setParameter('date', date('Y-m-d H:i:s', time()-86400 * $period))
        ->orderBy('p.createdAt', 'DESC');
      $query = $qb->getQuery();
      return $query->getResult();
   }
   
   public function findByCustomerName($first, $family) {
       $qb = $this->createQueryBuilder('p')
               ->where('p.firstName = :first')
               ->andWhere('p.lastName = :last')
               ->setParameter('first', $first)
               ->setParameter('last', $family)
               ->orderBy('p.createdAt', 'DESC');
       $query = $qb->getQuery();
       return $query->getResult();
   }
   
   public function countByCustomer($customer) {
       $qb = $this->createQueryBuilder('p')
               ->where('p.customer = : customer')
               ->setParameter('customer', $customer);
       $query = $qb->getQuery();
       return $query->getResult();
   }
}
