<?php

namespace Ibase\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRepository extends EntityRepository
{   
    public function getWithProduct($product_id = null)
    {
        if ($product_id) {
            
            $qb = $this->createQueryBuilder('j')
                    ->where('j.product = :product_id')
                    ->setParameter('product_id', $product_id);
            $query = $qb->getQuery();
            return $query->getResult();
        }
    }

  
}
