product:
    pattern:  /
    defaults: { _controller: "IbaseStoreBundle:Product:index" }
    
product_list:
    pattern:  /list
    defaults: { _controller: "IbaseStoreBundle:Product:list" }
    
product_list_category:
    pattern:  /category/{slug}
    defaults: { _controller: "IbaseStoreBundle:Product:listByCategory" } 

product_show:
    pattern:  /{id}/show
    defaults: { _controller: "IbaseStoreBundle:Product:show" }

product_new:
    pattern:  /new
    defaults: { _controller: "IbaseStoreBundle:Product:new" }

product_create:
    pattern:  /create
    defaults: { _controller: "IbaseStoreBundle:Product:create" }
    requirements: { _method: post }

product_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IbaseStoreBundle:Product:edit" }

product_update:
    pattern:  /{id}/update
    defaults: { _controller: "IbaseStoreBundle:Product:update" }
    requirements: { _method: post|put }

product_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IbaseStoreBundle:Product:delete" }
    requirements: { _method: post|delete }
