choose_a_item:
    pattern:  /
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:index" }

choose_a_item_show:
    pattern:  /{id}/show
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:show" }

choose_a_item_new:
    pattern:  /new
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:new" }

choose_a_item_create:
    pattern:  /create
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:create" }
    requirements: { _method: post }

choose_a_item_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:edit" }

choose_a_item_update:
    pattern:  /{id}/update
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:update" }
    requirements: { _method: post|put }

choose_a_item_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IbaseStoreBundle:PurchasePerItem:delete" }
    requirements: { _method: post|delete }
