Ibase\StoreBundle\Entity\Customer:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    email:
      type: string
      length: 255
      nullable: false
    first_name:
      type: string
      length: 255
      nullable: false
    last_name:
      type: string
      length: 255
      nullable: false
    street:
      type: string
      length: 255
      nullable: false
    town:
      type: string
      length: 255
      nullable: false
    state:
      type: string
      length: 255
      nullable: false
    country:
      type: string
      length: 255
      nullable: true
    postcode:
      type: string
      length: 16
      nullable: false
    contact:
      type: string
      length: 64
      nullable: true
    first_time:
      type: boolean
      nullable: true
#    uniqueConstraints:
#      search_idx:
#        columns: [ email, first_name, last_name ]
  oneToMany:
    purchase:
      targetEntity: Purchase
      mappedBy: customer
      cascade: [ "all" ]