Ibase\StoreBundle\Entity\Image:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: true
    ord:
      type: integer
      nullable: true
    path:
        type: string
        length: 255
        nullable: false
    updated:        # changed when files are uploaded, to force preUpdate and postUpdate to fire
      type:         datetime
      nullable:     true
  manyToOne:
    Product:
      targetEntity: Product
      inversedBy: Image
      joinColumns:
        product_id:
          referencedColumnName: id
      onDelete: cascade
  lifecycleCallbacks:
      prePersist:   [ lifecycleFileUpload ]
      preUpdate:    [ lifecycleFileUpload ]