Ibase\StoreBundle\Entity\PurchasePerItem:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    quantity:
      type: integer
      nullable: true

  manyToOne:
    purchase:
      targetEntity: Purchase
      inversedBy: purchasePerItem
      cascade: [ "all"]
      joinColumns:
        purchase_id:
          referencedColumnName: id
          nullable: false
    product:
      targetEntity: Product
      inversedBy: purchasePerItem
      joinColumns:
        product_id:
          referencedColumnName: id
