parameters:
#    ibase_app.example.class: Ibase\AppBundle\Example

services:
#    ibase_app.example:
#        class: %ibase_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
